vkApi:
  token: ${vkToken}
  appId: ${vkAppId}
usersScrape:
  interval: 10
db:
#  url: jdbc:postgresql://localhost/vk_api_client
  url: jdbc:h2:mem:vk_api_client;INIT=RUNSCRIPT FROM 'classpath:/script.sql'
  username: sa
  password: ''
server:
  port: 8080
